version: "1"

services:
  postgres:
    image: postgres:12.4
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  broker_app:
    image: pactfoundation/pact-broker:2.94.0.0
    links:
      - postgres
    ports:
      - 8085:9292
    environment:
      PACT_BROKER_BASIC_AUTH_USERNAME: pact
      PACT_BROKER_BASIC_AUTH_PASSWORD: pact
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: postgres
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres